# This is taken from https://github.com/Area69Lab/Recovery-Builder-NoKernel
# All credits goes to above repo

name: Building recovery

on:
  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
  MANIFEST_BRANCH: twrp-11
  DEVICE: X690B
  DT_LINK: https://github.com/pitekkate/twrp_infinix_X690
  DT_PATH: device/infinix/X690B
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-lates
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initializing environment
      run: |
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        docker rmi `docker images -q`
        git config --global user.name "pitekkate"
        git config --global user.email "pitekkate@gmail.com"
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get clean
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison aria2
        sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo chmod a+rx /usr/local/bin/repo

    - name: Sync recovery source and device tree
      run: |
        mkdir work
        cd work
        repo init -u $MANIFEST -b $MANIFEST_BRANCH --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
        repo sync -j4
        git clone $DT_LINK --depth=1 --single-branch $DT_PATH

    - name: Build
      run: |
        cd work && export ALLOW_MISSING_DEPENDENCIES=true && . build/envsetup.sh && lunch twrp_$DEVICE-eng && mka $TARGET

    - name: Upload recovery image
      run: |
        cd work/out/target/product/$DEVICE
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet recovery.img
